Highcharts.chart('container', {
    chart: {
        type: 'packedbubble',
        height: '100%'
    },
    title: {
        text: ' '
    },
    tooltip: {
        useHTML: true,
        pointFormat: '<b>{point.name}:</b> {point.value}'
    },
    plotOptions: {
        packedbubble: {
            minSize: '20%',
            maxSize: '100%',
            zMin: 0,
            zMax: 1000,
            dataLabels: {
                enabled: true,
                format: '{point.name}',
                filter: {
                    property: 'y',
                    operator: '>',
                    value: 250
                },
                style: {
                    color: 'black',
                    textOutline: 'none',
                    fontWeight: 'normal'
                }
            }
        }
    },
  
    series:
    [{'name': 'Male',
  'data': [{'name': 'kottarakkara sreedharan nair', 'value': 160},
   {'name': 'sp pillai', 'value': 215},
   {'name': 'thikkurissi sukumaran nair', 'value': 298},
   {'name': 'paravoor bharathan', 'value': 274},
   {'name': 'ts muthaiah', 'value': 163},
   {'name': 'prem nazir', 'value': 512},
   {'name': 'jose prakash', 'value': 295},
   {'name': 'sathyan', 'value': 148},
   {'name': 'adoor bhasi', 'value': 587},
   {'name': 'gk pillai', 'value': 118},
   {'name': 'bahadoor', 'value': 487},
   {'name': 'harikeshan thampi ', 'value': 114},
   {'name': 'manavalan joseph', 'value': 172},
   {'name': 'kp ummer', 'value': 351},
   {'name': 'jagathy sreekumar', 'value': 882},
   {'name': 'nellikkode bhaskaran', 'value': 161},
   {'name': 'prathapachandran', 'value': 284},
   {'name': 'sankaradi', 'value': 575},
   {'name': 'madhu', 'value': 348},
   {'name': 'kuthiravattam pappu', 'value': 399},
   {'name': 'kaduvakulam antony', 'value': 123},
   {'name': 'kunchan', 'value': 263},
   {'name': 'suresh gopi', 'value': 217},
   {'name': 'kalasala babu', 'value': 115},
   {'name': 'bobby kottarakkara', 'value': 129},
   {'name': 'alummoodan', 'value': 161},
   {'name': 'ci paul', 'value': 109},
   {'name': 'mala aravindan', 'value': 370},
   {'name': 'raghavan', 'value': 119},
   {'name': 'kozhikode narayanan nair', 'value': 108},
   {'name': 'vincent', 'value': 177},
   {'name': 'janardanan', 'value': 441},
   {'name': 'sudheer', 'value': 104},
   {'name': 'balan k nair', 'value': 241},
   {'name': 'kpac sunny', 'value': 147},
   {'name': 'mammootty', 'value': 396},
   {'name': 'cochin haneefa', 'value': 224},
   {'name': 'innocent', 'value': 434},
   {'name': 'jayan', 'value': 118},
   {'name': 'thilakan', 'value': 334},
   {'name': 'vijayaraghavan', 'value': 315},
   {'name': 'oduvil unnikrishnan', 'value': 203},
   {'name': 'mg soman', 'value': 403},
   {'name': 'sukumaran', 'value': 233},
   {'name': 'tp madhavan', 'value': 220},
   {'name': 'tg ravi', 'value': 167},
   {'name': 'sathar', 'value': 156},
   {'name': 'poojappura ravi', 'value': 140},
   {'name': 'maniyanpilla raju', 'value': 233},
   {'name': 'sreenivasan', 'value': 186},
   {'name': 'saikumar', 'value': 270},
   {'name': 'ratheesh', 'value': 161},
   {'name': 'nedumudi venu', 'value': 506},
   {'name': 'vk sreeraman', 'value': 164},
   {'name': 'sudheer karamana', 'value': 116},
   {'name': 'lalu alex', 'value': 247},
   {'name': 'bheeman raghu', 'value': 167},
   {'name': 'mohanlal', 'value': 339},
   {'name': 'jagannadha varma', 'value': 198},
   {'name': 'mamukkoya', 'value': 355},
   {'name': 'johny', 'value': 125},
   {'name': 'ashokan', 'value': 165},
   {'name': 'shanker', 'value': 125},
   {'name': 'murali', 'value': 160},
   {'name': 'indrans', 'value': 385},
   {'name': 'captain raju', 'value': 173},
   {'name': 'baiju', 'value': 132},
   {'name': 'augustine', 'value': 139},
   {'name': 'mukesh', 'value': 268},
   {'name': 'babu namboothiri', 'value': 120},
   {'name': 'sudheesh', 'value': 134},
   {'name': 'devan', 'value': 230},
   {'name': 'rajan p dev', 'value': 212},
   {'name': 'jagadish', 'value': 311},
   {'name': 'ganesh kumar', 'value': 133},
   {'name': 'shammi thilakan', 'value': 113},
   {'name': 'siddique', 'value': 360},
   {'name': 'nandhu', 'value': 141},
   {'name': 'kollam thulasi', 'value': 102},
   {'name': 'harishree ashokan', 'value': 208},
   {'name': 'sadiq', 'value': 158},
   {'name': 'jayaram', 'value': 188},
   {'name': 'narendra prasad', 'value': 117},
   {'name': 'manoj k jayan', 'value': 154},
   {'name': 'biju menon', 'value': 142},
   {'name': 'kalabhavan narayanankutty', 'value': 127},
   {'name': 'dileep', 'value': 140},
   {'name': 'anil murali', 'value': 105},
   {'name': 'baburaj', 'value': 109},
   {'name': 'kalabhavan mani', 'value': 221},
   {'name': 'salim kumar', 'value': 290},
   {'name': 'irshad', 'value': 105},
   {'name': 'kochu preman', 'value': 189},
   {'name': 'jayasurya', 'value': 104},
   {'name': 'kalabhavan shajohn', 'value': 127},
   {'name': 'suraj venjaramoodu', 'value': 260},
   {'name': 'shivaji guruvayoor', 'value': 140},
   {'name': 'sreejith ravi', 'value': 105},
   {'name': 'sasi kalinga', 'value': 104},
   {'name': 'aju varghese', 'value': 109},
   {'name': 'sunil sukhada', 'value': 173}]},
 {'name': 'Female', color:'pink',
  'data': [{'name': 'tr omana', 'value': 211},
   {'name': 'aranmula ponnamma', 'value': 158},
   {'name': 'adoor pankajam', 'value': 134},
   {'name': 'valsala menon', 'value': 181},
   {'name': 'adoor bhavani', 'value': 147},
   {'name': 'santhadevi', 'value': 130},
   {'name': 'sukumari', 'value': 728},
   {'name': 'kaviyoor ponnamma', 'value': 352},
   {'name': 'sheela', 'value': 213},
   {'name': 'meena (old)', 'value': 313},
   {'name': 'philomina', 'value': 222},
   {'name': 'sharada', 'value': 123},
   {'name': 'jayabharathi', 'value': 303},
   {'name': 'sreelatha namboothiri', 'value': 253},
   {'name': 'srividya', 'value': 201},
   {'name': 'kpac lalitha', 'value': 467},
   {'name': 'seema', 'value': 183},
   {'name': 'unnimary', 'value': 111},
   {'name': 'santhakumari', 'value': 235},
   {'name': 'jalaja', 'value': 103},
   {'name': 'ambika ', 'value': 103},
   {'name': 'kalpana', 'value': 183},
   {'name': 'zeenath', 'value': 101},
   {'name': 'urvasi', 'value': 125},
   {'name': 'ambika mohan', 'value': 205},
   {'name': 'kanakalatha', 'value': 138},
   {'name': 'bindu panicker', 'value': 161},
   {'name': 'ponnamma babu', 'value': 104},
   {'name': 'kulappulli leela', 'value': 119}]}]});
